# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitfs < Formula
  desc "FUSE filesystem for browsing contents of git repositories revisions"
  homepage "https://github.com/dsxack/gitfs"
  version "1.4.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dsxack/gitfs/releases/download/v1.4.5/gitfs_Darwin_x86_64.tar.gz"
      sha256 "2eeb0610836432ba15b14c4269fd4fe19f7cd4032070004f5e0e435d630dc9ca"

      def install
        bin.install "gitfs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dsxack/gitfs/releases/download/v1.4.5/gitfs_Darwin_arm64.tar.gz"
      sha256 "f92b008b55cf7c7bb7126c75822e500e4a8509a111322958422b3e6252f7fcc7"

      def install
        bin.install "gitfs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dsxack/gitfs/releases/download/v1.4.5/gitfs_Linux_arm64.tar.gz"
      sha256 "69b83d440f62d8295bee93e62048d9cb8b9bb5e9ccde9cce953ae0eab51bc0d4"

      def install
        bin.install "gitfs"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dsxack/gitfs/releases/download/v1.4.5/gitfs_Linux_x86_64.tar.gz"
      sha256 "983905203bffb7ac4bbc6ef30f31a482fe5f168e66bbd936198ca5b65e825f81"

      def install
        bin.install "gitfs"
      end
    end
  end

  depends_on "libfuse-dev" if OS.linux?
  depends_on cask: "osxfuse" if OS.mac?

  test do
    system "#{bin}/gitfs", "version"
  end
end
