# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitfs < Formula
  desc "FUSE filesystem for browsing contents of git repositories revisions"
  homepage "https://github.com/dsxack/gitfs"
  version "1.4.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dsxack/gitfs/releases/download/v1.4.5/gitfs_Darwin_x86_64.tar.gz"
      sha256 "f3d9eb54220f7b53a1a54f6c97111e1d36faf5f164fbdd96b375d539ac2e5c45"

      def install
        bin.install "gitfs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dsxack/gitfs/releases/download/v1.4.5/gitfs_Darwin_arm64.tar.gz"
      sha256 "a14981138a71f29ef004a9a4acf63889f2176b8047bb0c3f07b8ad46a1328b74"

      def install
        bin.install "gitfs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dsxack/gitfs/releases/download/v1.4.5/gitfs_Linux_arm64.tar.gz"
      sha256 "98ffa80802161ce88fa6b95917e00910d464aab885976e1523e1a76fa24cce17"

      def install
        bin.install "gitfs"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dsxack/gitfs/releases/download/v1.4.5/gitfs_Linux_x86_64.tar.gz"
      sha256 "5a204d485ad1aab2af036e9a46ad7282d73913c0ea0b423bdcbe86079ed4d4e0"

      def install
        bin.install "gitfs"
      end
    end
  end

  depends_on cask: "osxfuse" if OS.mac?
  depends_on "libfuse-dev" if OS.linux?

  test do
    system "#{bin}/gitfs", "version"
  end
end
