# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitfs < Formula
  desc "FUSE filesystem for browsing contents of git repositories revisions."
  homepage "https://github.com/dsxack/gitfs"
  version "1.4.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dsxack/gitfs/releases/download/v1.4.4/gitfs_Darwin_x86_64.tar.gz"
      sha256 "1c4db2a7482cd278a3f1b6c13b991a477c318cc9ff7e65968802066c2b687acd"

      def install
        bin.install "gitfs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dsxack/gitfs/releases/download/v1.4.4/gitfs_Darwin_arm64.tar.gz"
      sha256 "6da2516ce4e00c7c4da21a9a464f6d423212759bc8fba7347d2b4d78f8e8bca7"

      def install
        bin.install "gitfs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dsxack/gitfs/releases/download/v1.4.4/gitfs_Linux_arm64.tar.gz"
      sha256 "d477dce1c1142d4a83983e72a59a0a4e46947c12b0d5cdafcb6204a12f235f50"

      def install
        bin.install "gitfs"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dsxack/gitfs/releases/download/v1.4.4/gitfs_Linux_x86_64.tar.gz"
      sha256 "bddb134c2d72ee79dc8d0b42f47d4c937b14b908c17a98b0f9e9bf5bd16aa3fe"

      def install
        bin.install "gitfs"
      end
    end
  end

  test do
    system "#{bin}/gitfs version"
  end
end
